<a href="https://colab.research.google.com/github/giriprasathk0506/Giri/blob/main/MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
df=pd.read_csv("/content/sample_data/IPL.csv")
df

,Player,Team,Matches,Runs,Wickets,Strike_Rate,Average,Unnamed: 7
0,Virat Kohli,RCB,15,741,0,154.69,61.75,NaN
1,Rohit Sharma,MI,14,417,0,150.54,32.08,NaN
2,Shubman Gill,GT,15,890,0,157.80,59.33,NaN
3,KL Rahul,LSG,14,520,0,135.20,43.33,NaN
4,MS Dhoni,CSK,14,350,0,161.29,58.33,NaN
5,Ruturaj Gaikwad,CSK,15,590,0,147.50,42.14,NaN
6,Jasprit Bumrah,MI,14,25,20,125.00,6.25,NaN
7,Mohammed Shami,GT,15,18,28,90.00,4.50,NaN
8,Yuzvendra Chahal,RR,14,15,22,75.00,3.75,NaN
9,Rashid Khan,GT,15,90,24,145.16,15.00,NaN

SORTING

In [18]:
df.columns=df.columns.str.strip()
df.sort_values(by="Player",ascending=True)

,Player,Team,Matches,Runs,Wickets,Strike_Rate,Average,Unnamed: 7
6,Jasprit Bumrah,MI,14,25,20,125.00,6.25,NaN
3,KL Rahul,LSG,14,520,0,135.20,43.33,NaN
4,MS Dhoni,CSK,14,350,0,161.29,58.33,NaN
7,Mohammed Shami,GT,15,18,28,90.00,4.50,NaN
9,Rashid Khan,GT,15,90,24,145.16,15.00,NaN
1,Rohit Sharma,MI,14,417,0,150.54,32.08,NaN
5,Ruturaj Gaikwad,CSK,15,590,0,147.50,42.14,NaN
2,Shubman Gill,GT,15,890,0,157.80,59.33,NaN
0,Virat Kohli,RCB,15,741,0,154.69,61.75,NaN
8,Yuzvendra Chahal,RR,14,15,22,75.00,3.75,NaN

In [22]:
df.sort_values(by="Strike_Rate")

,Player,Team,Matches,Runs,Wickets,Strike_Rate,Average,Unnamed: 7
8,Yuzvendra Chahal,RR,14,15,22,75.00,3.75,NaN
7,Mohammed Shami,GT,15,18,28,90.00,4.50,NaN
6,Jasprit Bumrah,MI,14,25,20,125.00,6.25,NaN
3,KL Rahul,LSG,14,520,0,135.20,43.33,NaN
9,Rashid Khan,GT,15,90,24,145.16,15.00,NaN
5,Ruturaj Gaikwad,CSK,15,590,0,147.50,42.14,NaN
1,Rohit Sharma,MI,14,417,0,150.54,32.08,NaN
0,Virat Kohli,RCB,15,741,0,154.69,61.75,NaN
2,Shubman Gill,GT,15,890,0,157.80,59.33,NaN
4,MS Dhoni,CSK,14,350,0,161.29,58.33,NaN

In [23]:
df.sort_values(by=["Player","Runs"])

,Player,Team,Matches,Runs,Wickets,Strike_Rate,Average,Unnamed: 7
6,Jasprit Bumrah,MI,14,25,20,125.00,6.25,NaN
3,KL Rahul,LSG,14,520,0,135.20,43.33,NaN
4,MS Dhoni,CSK,14,350,0,161.29,58.33,NaN
7,Mohammed Shami,GT,15,18,28,90.00,4.50,NaN
9,Rashid Khan,GT,15,90,24,145.16,15.00,NaN
1,Rohit Sharma,MI,14,417,0,150.54,32.08,NaN
5,Ruturaj Gaikwad,CSK,15,590,0,147.50,42.14,NaN
2,Shubman Gill,GT,15,890,0,157.80,59.33,NaN
0,Virat Kohli,RCB,15,741,0,154.69,61.75,NaN
8,Yuzvendra Chahal,RR,14,15,22,75.00,3.75,NaN

CREATING NEW COLUMN

In [56]:
df["Tournament"] = "IPL"
df

,Player,Team,Matches,Runs,Wickets,Strike_Rate,Average,Unnamed: 7,Tournament,Player_Length,Player_surename,WINNER_LENGTH
0,Virat Kohli,RCB,15,741,0,154.69,61.75,NaN,IPL,17,17,17
1,Rohit Sharma,MI,14,417,0,150.54,32.08,NaN,IPL,17,17,17
2,Shubman Gill,GT,15,890,0,157.80,59.33,NaN,IPL,17,17,17
3,KL Rahul,LSG,14,520,0,135.20,43.33,NaN,IPL,17,17,17
4,MS Dhoni,CSK,14,350,0,161.29,58.33,NaN,IPL,17,17,17
5,Ruturaj Gaikwad,CSK,15,590,0,147.50,42.14,NaN,IPL,17,17,17
6,Jasprit Bumrah,MI,14,25,20,125.00,6.25,NaN,IPL,17,17,17
7,Mohammed Shami,GT,15,18,28,90.00,4.50,NaN,IPL,17,17,17
8,Yuzvendra Chahal,RR,14,15,22,75.00,3.75,NaN,IPL,17,17,17
9,Rashid Khan,GT,15,90,24,145.16,15.00,NaN,IPL,17,17,17

In [45]:
df['WINNER_LENGTH'] = df['Player'].str.len()
df

,Player,Team,Matches,Runs,Wickets,Strike_Rate,Average,Unnamed: 7,Tournament,Player_Length,Player_surename,WINNER_LENGTH
0,Virat Kohli,RCB,15,741,0,154.69,61.75,NaN,IPL,17,17,17
1,Rohit Sharma,MI,14,417,0,150.54,32.08,NaN,IPL,17,17,17
2,Shubman Gill,GT,15,890,0,157.80,59.33,NaN,IPL,17,17,17
3,KL Rahul,LSG,14,520,0,135.20,43.33,NaN,IPL,17,17,17
4,MS Dhoni,CSK,14,350,0,161.29,58.33,NaN,IPL,17,17,17
5,Ruturaj Gaikwad,CSK,15,590,0,147.50,42.14,NaN,IPL,17,17,17
6,Jasprit Bumrah,MI,14,25,20,125.00,6.25,NaN,IPL,17,17,17
7,Mohammed Shami,GT,15,18,28,90.00,4.50,NaN,IPL,17,17,17
8,Yuzvendra Chahal,RR,14,15,22,75.00,3.75,NaN,IPL,17,17,17
9,Rashid Khan,GT,15,90,24,145.16,15.00,NaN,IPL,17,17,17

GROUP BY

In [61]:
team_runs = df.groupby("Team")["Runs"].sum()
team_runs

Team
CSK      940
GT       998
LSG      520
MI       442
RCB      741
RR        15
Name: Runs, dtype: int64

In [63]:
avg_runs = df.groupby("Team")["Runs"].mean()
avg_runs

Team
CSK      470.000000
GT       332.666667
LSG      520.000000
MI       221.000000
RCB      741.000000
RR        15.000000
Name: Runs, dtype: float64

In [65]:
result = df.groupby("Team")["Runs"].agg(["sum", "mean", "max", "min", "count"])
result

       sum        mean  max  min  count
Team
CSK    940  470.000000  590  350      2
GT     998  332.666667  890   18      3
LSG    520  520.000000  520  520      1
MI     442  221.000000  417   25      2
RCB    741  741.000000  741  741      1
RR      15   15.000000   15   15      1

FILTERING RECORDS BASED ON CONDITIONS

In [67]:
result = df[df['Runs'] > 50]
result

,Player,Team,Matches,Runs,Wickets,Strike_Rate,Average,Unnamed: 7,Tournament,Player_Length,Player_surename,WINNER_LENGTH
0,Virat Kohli,RCB,15,741,0,154.69,61.75,NaN,IPL,17,17,17
1,Rohit Sharma,MI,14,417,0,150.54,32.08,NaN,IPL,17,17,17
2,Shubman Gill,GT,15,890,0,157.80,59.33,NaN,IPL,17,17,17
3,KL Rahul,LSG,14,520,0,135.20,43.33,NaN,IPL,17,17,17
4,MS Dhoni,CSK,14,350,0,161.29,58.33,NaN,IPL,17,17,17
5,Ruturaj Gaikwad,CSK,15,590,0,147.50,42.14,NaN,IPL,17,17,17
9,Rashid Khan,GT,15,90,24,145.16,15.00,NaN,IPL,17,17,17

In [68]:
result = df[(df['Team'] == 'MI') | (df['Team'] == 'CSK')]
result

Empty DataFrame
Columns: [Player, Team, Matches, Runs, Wickets, Strike_Rate, Average, Unnamed: 7, Tournament, Player_Length, Player_surename, WINNER_LENGTH]
Index: []

In [70]:
df.rename(columns={'Runs':'Total_Runs'}, inplace=True)
df.head()

,Player,Team,Matches,Total_Runs,Wickets,Strike_Rate,Average,Unnamed: 7,Tournament,Player_Length,Player_surename,WINNER_LENGTH
0,Virat Kohli,RCB,15,741,0,154.69,61.75,NaN,IPL,17,17,17
1,Rohit Sharma,MI,14,417,0,150.54,32.08,NaN,IPL,17,17,17
2,Shubman Gill,GT,15,890,0,157.80,59.33,NaN,IPL,17,17,17
3,KL Rahul,LSG,14,520,0,135.20,43.33,NaN,IPL,17,17,17
4,MS Dhoni,CSK,14,350,0,161.29,58.33,NaN,IPL,17,17,17